name: Build and Release Ignition Files

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Butane
        run: |
          BUTANE_VERSION=$(curl -s https://api.github.com/repos/coreos/butane/releases/latest | grep tag_name | cut -d '"' -f 4)
          curl -L -o butane "https://github.com/coreos/butane/releases/download/${BUTANE_VERSION}/butane-x86_64-unknown-linux-gnu"
          chmod +x butane
          sudo mv butane /usr/local/bin/

      - run: cd ada

      - name: Run Make
        run: make all

      - name: Create Release and Upload Assets
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes \
            ada0.ign ada1.ign ada2.ign ada3.ign ada4.ign

      - name: Upload Artifacts (Action Run)
        uses: actions/upload-artifact@v4
        with:
          name: ignition-files
          path: "*.ign"
